/**
 * Step 4 — Generate src/database.ts from database/data/3_enriched.json.
 *
 * Input:  database/data/2_base.json     (all words — source of truth for the word list)
 *         database/data/3_enriched.json (partial enrichment — may be incomplete)
 * Output: src/database.ts
 *
 * Words in 2_base.json but not yet in 3_enriched.json get empty enrichment
 * defaults so database.ts always contains every word even during a partial run.
 *
 * Run: npx tsx scripts/database/4_generate_database.ts
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import type { BaseWord, UnifiedWord } from "../constants.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const basePath = path.join(__dirname, "data", "2_base.json");
const enrichedPath = path.join(__dirname, "data", "3_enriched.json");
const outPath = path.join(__dirname, "..", "..", "src", "database.ts");

const TYPE_MAP: Record<string, string> = {
  noun: "Type.N",
  verb: "Type.V",
  adjective: "Type.Adj",
  adverb: "Type.Adv",
  pronoun: "Type.Pron",
  question_pronoun: "Type.QPron",
  numeral: "Type.Num",
  measure_word: "Type.MW",
  preposition: "Type.Prep",
  conjunction: "Type.Conj",
  particle: "Type.Part",
  interjection: "Type.Interj",
  auxiliary_verb: "Type.AuxV",
  modal_verb: "Type.ModV",
  time_word: "Type.TimeW",
  location_word: "Type.LocW",
  expression: "Type.Expr",
  proper_noun: "Type.PN",
};

function q(str: string): string {
  return JSON.stringify(str);
}

function formatExample(ex: { zh: string; pinyin: string; en: string }): string {
  return `    { zh: ${q(ex.zh)}, pinyin: ${q(ex.pinyin)}, en: ${q(ex.en)} }`;
}

function formatWord(w: UnifiedWord): string {
  const types = (w.types ?? ["noun"])
    .map((t) => TYPE_MAP[t] ?? "Type.N")
    .join(",");
  const sinoVi = w.sino_vi ? q(w.sino_vi) : "null";
  const examples = (w.examples ?? []).map(formatExample).join(",\n");
  const synonyms = (w.synonyms ?? []).map(q).join(", ");
  const antonyms = (w.antonyms ?? []).map(q).join(", ");

  return [
    `  {`,
    `    chinese:${q(w.chinese)}, pinyin:${q(w.pinyin)}, en:${q(w.en)}, vi:${q(w.vi ?? "")}, sino_vi:${sinoVi},`,
    `    types:[${types}], hsk:${w.hsk},`,
    `    zh:${q(w.zh ?? "")},`,
    `    examples:[`,
    examples ? examples + "," : "",
    `    ],`,
    `    synonyms:[${synonyms}],`,
    `    antonyms:[${antonyms}],`,
    `  },`,
  ].join("\n");
}

function generate(): void {
  if (!fs.existsSync(basePath)) {
    console.error(`Missing ${basePath} — run database/2_concat_base.ts first`);
    process.exit(1);
  }

  const base: BaseWord[] = JSON.parse(fs.readFileSync(basePath, "utf-8"));

  const enriched: Record<string, UnifiedWord> = fs.existsSync(enrichedPath)
    ? JSON.parse(fs.readFileSync(enrichedPath, "utf-8"))
    : {};

  const words: UnifiedWord[] = base.map(
    (w) =>
      enriched[w.chinese] ?? {
        ...w,
        vi: "",
        sino_vi: null,
        types: ["noun"],
        zh: "",
        examples: [],
        synonyms: [],
        antonyms: [],
      },
  );

  const byLevel: Record<number, UnifiedWord[]> = {};
  for (const w of words) {
    (byLevel[w.hsk] ??= []).push(w);
  }

  const lines: string[] = [];
  lines.push(
    `// Auto-generated by scripts/database/4_generate_database.ts — do not edit by hand`,
  );
  lines.push(
    `// Run: npx tsx scripts/database/3_enrich_word.ts && npx tsx scripts/database/4_generate_database.ts`,
  );
  lines.push(``);
  lines.push(`enum Type {`);
  lines.push(`  N = "noun",`);
  lines.push(`  V = "verb",`);
  lines.push(`  Adj = "adjective",`);
  lines.push(`  Adv = "adverb",`);
  lines.push(`  Pron = "pronoun",`);
  lines.push(`  QPron = "question_pronoun",`);
  lines.push(`  Num = "numeral",`);
  lines.push(`  MW = "measure_word",`);
  lines.push(`  Prep = "preposition",`);
  lines.push(`  Conj = "conjunction",`);
  lines.push(`  Part = "particle",`);
  lines.push(`  Interj = "interjection",`);
  lines.push(`  AuxV = "auxiliary_verb",`);
  lines.push(`  ModV = "modal_verb",`);
  lines.push(`  TimeW = "time_word",`);
  lines.push(`  LocW = "location_word",`);
  lines.push(`  Expr = "expression",`);
  lines.push(`  PN = "proper_noun",`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`type Word = {`);
  lines.push(`  chinese: string;`);
  lines.push(`  pinyin: string;`);
  lines.push(`  en: string;`);
  lines.push(`  vi: string;`);
  lines.push(`  sino_vi: string | null;`);
  lines.push(`  types: Type[];`);
  lines.push(`  hsk: number;`);
  lines.push(`  zh: string;`);
  lines.push(`  examples: Array<{ zh: string; pinyin: string; en: string }>;`);
  lines.push(`  synonyms: string[];`);
  lines.push(`  antonyms: string[];`);
  lines.push(`};`);
  lines.push(``);
  lines.push(`const WORDS: Word[] = [`);

  for (let level = 1; level <= 6; level++) {
    const group = byLevel[level] ?? [];
    lines.push(`  // HSK ${level} (${group.length} words)`);
    for (const w of group) {
      lines.push(formatWord(w));
    }
    lines.push(``);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export { WORDS, type Type, type Word };`);
  lines.push(``);

  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");

  const total = words.length;
  const withZh = words.filter((w) => w.zh).length;
  console.log(`Generated ${outPath}`);
  console.log(`Total words: ${total} (${withZh} with zh enrichment)`);
  for (let l = 1; l <= 6; l++) {
    console.log(`  HSK ${l}: ${(byLevel[l] ?? []).length}`);
  }
}

generate();
