// Auto-generated by scripts/generate-enrichments-ts.mjs — do not edit by hand
// Run: node scripts/enrich-learn.mjs && node scripts/generate-enrichments-ts.mjs

export type Enrichment = {
  explanation_zh: string;
  examples: Array<{ zh: string; pinyin: string; en: string }>;
  synonyms: Array<{ chinese: string; pinyin: string; en: string }>;
  antonyms: Array<{ chinese: string; pinyin: string; en: string }>;
};

export const ENRICHMENTS: Record<string, Enrichment> = {
  "爱": {
    explanation_zh: "爱是一种很强的感情，表示喜欢某个人或某个东西。",
    examples: [
    { zh: "我爱我的爸爸和妈妈。", pinyin: "Wǒ ài wǒ de bàba hé māma.", en: "I love my dad and mom." },
    { zh: "她爱吃苹果。", pinyin: "Tā ài chī píngguǒ.", en: "She loves eating apples." },
    { zh: "我们都爱我们的国家。", pinyin: "Wǒmen dōu ài wǒmen de guójiā.", en: "We all love our country." },
    ],
    synonyms: [
    { chinese: "喜欢", pinyin: "xǐhuān", en: "like; love" },
    ],
    antonyms: [
    { chinese: "恨", pinyin: "hèn", en: "hate" },
    ],
  },
  "八": {
    explanation_zh: "八是一个数字，在七和九之间。",
    examples: [
    { zh: "我有八个苹果。", pinyin: "Wǒ yǒu bā ge píngguǒ.", en: "I have eight apples." },
    { zh: "今天是八月十五号。", pinyin: "Jīntiān shì bā yuè shíwǔ hào.", en: "Today is August 15th." },
    { zh: "他八岁了。", pinyin: "Tā bā suì le.", en: "He is eight years old." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "爸爸": {
    explanation_zh: "爸爸是男性的父亲，是家里的男性长辈。",
    examples: [
    { zh: "我的爸爸在公司工作。", pinyin: "Wǒ de bàba zài gōngsī gōngzuò.", en: "My dad works at a company." },
    { zh: "爸爸每天都很忙。", pinyin: "Bàba měi tiān dōu hěn máng.", en: "Dad is busy every day." },
    { zh: "我喜欢和爸爸一起玩。", pinyin: "Wǒ xǐhuān hé bàba yīqǐ wán.", en: "I like to play with dad." },
    ],
    synonyms: [
    { chinese: "父亲", pinyin: "fùqin", en: "father" },
    ],
    antonyms: [
    { chinese: "妈妈", pinyin: "māma", en: "mom" },
    ],
  },
  "杯子": {
    explanation_zh: "杯子是用来喝水或喝饮料的容器。",
    examples: [
    { zh: "请给我一个杯子。", pinyin: "Qǐng gěi wǒ yī ge bēizi.", en: "Please give me a cup." },
    { zh: "这个杯子很漂亮。", pinyin: "Zhège bēizi hěn piàoliang.", en: "This cup is very beautiful." },
    { zh: "我用杯子喝茶。", pinyin: "Wǒ yòng bēizi hē chá.", en: "I drink tea with a cup." },
    ],
    synonyms: [
    { chinese: "杯", pinyin: "bēi", en: "cup" },
    ],
    antonyms: [
    ],
  },
  "北京": {
    explanation_zh: "北京是中国的首都，是一个很大的城市。",
    examples: [
    { zh: "北京在中国的北方。", pinyin: "Běijīng zài Zhōngguó de běifāng.", en: "Beijing is in the north of China." },
    { zh: "我想去北京旅游。", pinyin: "Wǒ xiǎng qù Běijīng lǚyóu.", en: "I want to travel to Beijing." },
    { zh: "北京有很多名胜古迹。", pinyin: "Běijīng yǒu hěnduō míngshèng gǔjī.", en: "Beijing has many famous historical sites." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "本": {
    explanation_zh: "本是量词，用来计算书、杂志等出版物的数量。也可以表示根本、原本的意思。",
    examples: [
    { zh: "我有三本书。", pinyin: "Wǒ yǒu sān běn shū.", en: "I have three books." },
    { zh: "这本词典很有用。", pinyin: "Zhè běn cídiǎn hěn yǒuyòng.", en: "This dictionary is very useful." },
    { zh: "我买了一本中文杂志。", pinyin: "Wǒ mǎile yī běn zhōngwén zázhì.", en: "I bought a Chinese magazine." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "不客气": {
    explanation_zh: "不客气是礼貌用语，用来回应别人的感谢。表示不需要道谢，很自然、很亲切。",
    examples: [
    { zh: "谢谢你！不客气。", pinyin: "Xièxie nǐ! Bú kèqi.", en: "Thank you! You're welcome." },
    { zh: "对不起。不客气，没关系。", pinyin: "Duìbùqǐ. Bú kèqi, méi guānxi.", en: "Sorry. Don't worry about it, it's fine." },
    { zh: "帮你的忙，不客气。", pinyin: "Bāng nǐ de máng, bú kèqi.", en: "Happy to help you, no need to be polite." },
    ],
    synonyms: [
    { chinese: "没关系", pinyin: "méi guānxi", en: "it doesn't matter" },
    ],
    antonyms: [
    ],
  },
  "不": {
    explanation_zh: "不是否定词，用来表示否定、拒绝或反对。是中文里最常用的否定词。",
    examples: [
    { zh: "我不喜欢喝咖啡。", pinyin: "Wǒ bù xǐhuān hē kāfēi.", en: "I don't like drinking coffee." },
    { zh: "这不是我的书。", pinyin: "Zhè búshì wǒ de shū.", en: "This is not my book." },
    { zh: "他不去参加聚会。", pinyin: "Tā búqù cānjiā jùhuì.", en: "He is not going to the party." },
    ],
    synonyms: [
    { chinese: "没有", pinyin: "méiyǒu", en: "don't have; didn't" },
    ],
    antonyms: [
    { chinese: "是", pinyin: "shì", en: "is; yes" },
    ],
  },
  "菜": {
    explanation_zh: "菜是指做好的食物或蔬菜。在餐厅里，菜是指各种饭菜。在厨房里，菜也可以指新鲜的蔬菜。",
    examples: [
    { zh: "这道菜很好吃。", pinyin: "Zhè dào cài hěn hǎochī.", en: "This dish is very delicious." },
    { zh: "我喜欢吃蔬菜。", pinyin: "Wǒ xǐhuān chī shūcài.", en: "I like eating vegetables." },
    { zh: "妈妈在做晚餐的菜。", pinyin: "Māma zài zuò wǎncān de cài.", en: "Mom is preparing dinner dishes." },
    ],
    synonyms: [
    { chinese: "蔬菜", pinyin: "shūcài", en: "vegetables" },
    { chinese: "饭菜", pinyin: "fàncài", en: "food; meal" },
    ],
    antonyms: [
    ],
  },
  "茶": {
    explanation_zh: "茶是一种饮料，用茶叶泡热水喝。茶在中国文化里很重要，有很长的历史。",
    examples: [
    { zh: "我每天喝茶。", pinyin: "Wǒ měi tiān hē chá.", en: "I drink tea every day." },
    { zh: "你想喝一杯茶吗？", pinyin: "Nǐ xiǎng hē yī bēi chá ma?", en: "Would you like to have a cup of tea?" },
    { zh: "中国茶很有名。", pinyin: "Zhōngguó chá hěn yǒumíng.", en: "Chinese tea is very famous." },
    ],
    synonyms: [
    ],
    antonyms: [
    { chinese: "咖啡", pinyin: "kāfēi", en: "coffee" },
    ],
  },
  "吃": {
    explanation_zh: "吃是指用嘴巴把食物放进去，然后咀嚼和吞下去。这是人每天都要做的事情。",
    examples: [
    { zh: "我每天早上吃早饭。", pinyin: "Wǒ měi tiān zǎo shang chī zǎo fàn.", en: "I eat breakfast every morning." },
    { zh: "你想吃什么？", pinyin: "Nǐ xiǎng chī shén me?", en: "What do you want to eat?" },
    { zh: "我们一起去吃饭吧。", pinyin: "Wǒ men yī qǐ qù chī fàn ba.", en: "Let's go eat together." },
    ],
    synonyms: [
    { chinese: "进食", pinyin: "jìn shí", en: "consume food" },
    ],
    antonyms: [
    ],
  },
  "出租车": {
    explanation_zh: "出租车是一种可以租用的汽车，司机会根据路程收费。在城市里很常见。",
    examples: [
    { zh: "我坐出租车去机场。", pinyin: "Wǒ zuò chūzūchē qù jī chǎng.", en: "I took a taxi to the airport." },
    { zh: "这辆出租车很干净。", pinyin: "Zhè liàng chūzūchē hěn gān jìng.", en: "This taxi is very clean." },
    { zh: "出租车的价格很贵。", pinyin: "Chūzūchē de jià gé hěn guì.", en: "Taxi fares are very expensive." },
    ],
    synonyms: [
    { chinese: "的士", pinyin: "de shì", en: "taxi" },
    { chinese: "计程车", pinyin: "jì chéng chē", en: "cab" },
    ],
    antonyms: [
    ],
  },
  "打电话": {
    explanation_zh: "打电话是指用电话和别人说话。打是动词，表示进行某个动作。",
    examples: [
    { zh: "我昨天打电话给妈妈。", pinyin: "Wǒ zuó tiān dǎ diànhuà gěi mā ma.", en: "I called my mom yesterday." },
    { zh: "你能帮我打电话吗？", pinyin: "Nǐ néng bāng wǒ dǎ diànhuà ma?", en: "Can you make a phone call for me?" },
    { zh: "他正在打电话。", pinyin: "Tā zhèng zài dǎ diànhuà.", en: "He is making a phone call." },
    ],
    synonyms: [
    { chinese: "通电话", pinyin: "tōng diànhuà", en: "have a phone call" },
    ],
    antonyms: [
    ],
  },
  "大": {
    explanation_zh: "大表示体积、面积或数量很多，和小相反。这是一个很常用的形容词。",
    examples: [
    { zh: "这是一个大房子。", pinyin: "Zhè shì yī ge dà fáng zi.", en: "This is a big house." },
    { zh: "中国很大。", pinyin: "Zhōng guó hěn dà.", en: "China is very large." },
    { zh: "我喜欢大的苹果。", pinyin: "Wǒ xǐ huan dà de píng guǒ.", en: "I like big apples." },
    ],
    synonyms: [
    { chinese: "巨大", pinyin: "jù dà", en: "huge" },
    { chinese: "宽敞", pinyin: "kuān chǎng", en: "spacious" },
    ],
    antonyms: [
    { chinese: "小", pinyin: "xiǎo", en: "small" },
    ],
  },
  "的": {
    explanation_zh: "的是一个虚词，用来表示所有关系。它连接名词和名词，表示前面的名词拥有后面的名词。",
    examples: [
    { zh: "这是我的书。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." },
    { zh: "那是老师的办公室。", pinyin: "Nà shì lǎo shī de bàn gōng shì.", en: "That is the teacher's office." },
    { zh: "我朋友的妹妹很聪明。", pinyin: "Wǒ péng you de mèi mei hěn cōng ming.", en: "My friend's younger sister is very smart." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "点": {
    explanation_zh: "点表示很小的圆形标记，也可以表示时间。比如一个点、两个点，或者三点钟。",
    examples: [
    { zh: "这个句子的最后有一个点。", pinyin: "Zhège jùzi de zuìhòu yǒu yī ge diǎn.", en: "There is a dot at the end of this sentence." },
    { zh: "现在是三点钟。", pinyin: "Xiànzài shì sān diǎn zhōng.", en: "It is three o'clock now." },
    { zh: "我想要一点糖。", pinyin: "Wǒ xiǎngyào yī diǎn táng.", en: "I want a little sugar." },
    ],
    synonyms: [
    { chinese: "小圆点", pinyin: "xiǎo yuándian", en: "small dot" },
    ],
    antonyms: [
    ],
  },
  "电脑": {
    explanation_zh: "电脑是一种机器，可以用来工作、学习和玩游戏。它有屏幕、键盘和鼠标。",
    examples: [
    { zh: "我每天都用电脑工作。", pinyin: "Wǒ měi tiān dōu yòng diànnǎo gōngzuò.", en: "I use a computer to work every day." },
    { zh: "这台电脑很新。", pinyin: "Zhè tái diànnǎo hěn xīn.", en: "This computer is very new." },
    { zh: "我的电脑坏了。", pinyin: "Wǒ de diànnǎo huài le.", en: "My computer is broken." },
    ],
    synonyms: [
    { chinese: "计算机", pinyin: "jìsuànjī", en: "computer" },
    ],
    antonyms: [
    ],
  },
  "电视": {
    explanation_zh: "电视是一种机器，可以看新闻、电影和各种节目。很多人喜欢在家里看电视。",
    examples: [
    { zh: "晚上我喜欢看电视。", pinyin: "Wǎnshang wǒ xǐhuān kàn diànshì.", en: "I like to watch television in the evening." },
    { zh: "请把电视关掉。", pinyin: "Qǐng bǎ diànshì guāndiào.", en: "Please turn off the TV." },
    { zh: "这个电视节目很有意思。", pinyin: "Zhège diànshì jiémù hěn yǒu yìsi.", en: "This TV program is very interesting." },
    ],
    synonyms: [
    { chinese: "电视机", pinyin: "diànshìjī", en: "television set" },
    ],
    antonyms: [
    ],
  },
  "电影": {
    explanation_zh: "电影是一种艺术形式，用摄像机拍摄的故事，在电影院或电视上放映。人们去电影院看电影很开心。",
    examples: [
    { zh: "昨天我看了一部很好的电影。", pinyin: "Zuótiān wǒ kàn le yī bù hěn hǎo de diànyǐng.", en: "I watched a very good movie yesterday." },
    { zh: "你喜欢看什么电影？", pinyin: "Nǐ xǐhuān kàn shénme diànyǐng?", en: "What kind of movies do you like to watch?" },
    { zh: "这个周末我们去电影院看电影。", pinyin: "Zhège zhōumò wǒmen qù diànyǐngyuàn kàn diànyǐng.", en: "We will go to the cinema to watch a movie this weekend." },
    ],
    synonyms: [
    { chinese: "影片", pinyin: "yǐngpiàn", en: "film" },
    { chinese: "电影片", pinyin: "diànyǐngpiàn", en: "movie" },
    ],
    antonyms: [
    ],
  },
  "东西": {
    explanation_zh: "东西是一个通用词，可以指任何物品或东西。也可以表示方向，东边和西边。",
    examples: [
    { zh: "这个房间里有很多东西。", pinyin: "Zhège fángjiān lǐ yǒu hěn duō dōngxi.", en: "There are many things in this room." },
    { zh: "你买了什么东西？", pinyin: "Nǐ mǎi le shénme dōngxi?", en: "What things did you buy?" },
    { zh: "不要乱扔东西。", pinyin: "Búyào luàn rēng dōngxi.", en: "Don't throw things around carelessly." },
    ],
    synonyms: [
    { chinese: "物品", pinyin: "wùpǐn", en: "items" },
    { chinese: "东西", pinyin: "dōngxi", en: "stuff" },
    ],
    antonyms: [
    ],
  },
  "都": {
    explanation_zh: "表示全部、整体，用来说明所有的人或事物。可以用在句子中间或前面。",
    examples: [
    { zh: "我们都是学生。", pinyin: "Wǒmen dōu shì xuésheng.", en: "We are all students." },
    { zh: "他们都喜欢吃米饭。", pinyin: "Tāmen dōu xǐhuān chī mǐfàn.", en: "They all like to eat rice." },
    { zh: "这些书我都读过。", pinyin: "Zhèxiē shū wǒ dōu dúguò.", en: "I have read all of these books." },
    ],
    synonyms: [
    { chinese: "全部", pinyin: "quánbù", en: "all; entire" },
    { chinese: "一起", pinyin: "yīqǐ", en: "together" },
    ],
    antonyms: [
    ],
  },
  "读": {
    explanation_zh: "表示看书或学习，是一个常用的动词。可以指读书、读文章或读任何文字内容。",
    examples: [
    { zh: "我每天读书。", pinyin: "Wǒ měitiān dúshū.", en: "I read books every day." },
    { zh: "他在读一本中文书。", pinyin: "Tā zài dú yī běn zhōngwén shū.", en: "He is reading a Chinese book." },
    { zh: "你读过这个故事吗？", pinyin: "Nǐ dúguò zhège gùshì ma?", en: "Have you read this story?" },
    ],
    synonyms: [
    { chinese: "看书", pinyin: "kànshū", en: "to read books" },
    { chinese: "学习", pinyin: "xuéxí", en: "to study" },
    ],
    antonyms: [
    ],
  },
  "对不起": {
    explanation_zh: "用来表示道歉或认错，是一个很有礼貌的表达方式。在日常生活中经常使用。",
    examples: [
    { zh: "对不起，我迟到了。", pinyin: "Duìbuqǐ, wǒ chídào le.", en: "Sorry, I am late." },
    { zh: "对不起，我不知道。", pinyin: "Duìbuqǐ, wǒ búzhīdào.", en: "Sorry, I don't know." },
    { zh: "对不起，请原谅我。", pinyin: "Duìbuqǐ, qǐng yuányuànliàng wǒ.", en: "Sorry, please forgive me." },
    ],
    synonyms: [
    { chinese: "抱歉", pinyin: "bàoqiàn", en: "sorry; apologize" },
    { chinese: "不好意思", pinyin: "búhǎo yìsi", en: "sorry; embarrassed" },
    ],
    antonyms: [
    ],
  },
  "多": {
    explanation_zh: "表示数量很大或很多，是一个常用的形容词。可以修饰名词或用在句子中。",
    examples: [
    { zh: "这里有很多人。", pinyin: "Zhèlǐ yǒu hěnduō rén.", en: "There are many people here." },
    { zh: "我有多个朋友。", pinyin: "Wǒ yǒu duō ge péngyou.", en: "I have many friends." },
    { zh: "他吃了很多米饭。", pinyin: "Tā chīle hěnduō mǐfàn.", en: "He ate a lot of rice." },
    ],
    synonyms: [
    { chinese: "很多", pinyin: "hěnduō", en: "many; a lot" },
    { chinese: "许多", pinyin: "xǔduō", en: "many; numerous" },
    ],
    antonyms: [
    { chinese: "少", pinyin: "shǎo", en: "few; little" },
    ],
  },
  "多少": {
    explanation_zh: "用来提问数量，可以问有多少个人、多少件东西或多少钱。是一个很实用的疑问词。",
    examples: [
    { zh: "你有多少本书？", pinyin: "Nǐ yǒu duōshao běn shū?", en: "How many books do you have?" },
    { zh: "这个多少钱？", pinyin: "Zhège duōshao qián?", en: "How much is this?" },
    { zh: "班里有多少个学生？", pinyin: "Bānlǐ yǒu duōshao ge xuésheng?", en: "How many students are in the class?" },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "儿子": {
    explanation_zh: "儿子是男孩子，是父亲和母亲的孩子。",
    examples: [
    { zh: "他有一个儿子和一个女儿。", pinyin: "Tā yǒu yīgè érzi hé yīgè nǚ'ér.", en: "He has one son and one daughter." },
    { zh: "我的儿子今年十岁。", pinyin: "Wǒ de érzi jīnnián shí suì.", en: "My son is ten years old this year." },
    { zh: "儿子喜欢和爸爸一起玩。", pinyin: "Érzi xǐhuān hé bàba yīqǐ wán.", en: "The son likes to play with his father." },
    ],
    synonyms: [
    { chinese: "男孩", pinyin: "nánhái", en: "boy" },
    ],
    antonyms: [
    { chinese: "女儿", pinyin: "nǚ'ér", en: "daughter" },
    ],
  },
  "二": {
    explanation_zh: "二是数字，表示一加一的结果。",
    examples: [
    { zh: "一加一等于二。", pinyin: "Yī jiā yī děngyú èr.", en: "One plus one equals two." },
    { zh: "我有两个苹果，你有二个橙子。", pinyin: "Wǒ yǒu liǎng ge píngguǒ, nǐ yǒu èr ge chéngzi.", en: "I have two apples, and you have two oranges." },
    { zh: "第二个房间在楼上。", pinyin: "Dì-èr ge fángjiān zài lóushang.", en: "The second room is upstairs." },
    ],
    synonyms: [
    { chinese: "两", pinyin: "liǎng", en: "two" },
    ],
    antonyms: [
    ],
  },
  "饭店": {
    explanation_zh: "饭店是吃饭的地方，也可以是住宿的地方。",
    examples: [
    { zh: "我们在饭店吃午饭。", pinyin: "Wǒmen zài fàndiàn chī wǔfàn.", en: "We eat lunch at the restaurant." },
    { zh: "这个饭店的菜很好吃。", pinyin: "Zhège fàndiàn de cài hěn hǎochī.", en: "The dishes at this restaurant are very delicious." },
    { zh: "我们在饭店住了三个晚上。", pinyin: "Wǒmen zài fàndiàn zhù le sān ge wǎnshang.", en: "We stayed at the hotel for three nights." },
    ],
    synonyms: [
    { chinese: "餐厅", pinyin: "cāntīng", en: "restaurant" },
    { chinese: "酒店", pinyin: "jiǔdiàn", en: "hotel" },
    ],
    antonyms: [
    ],
  },
  "飞机": {
    explanation_zh: "飞机是在天空飞行的交通工具，可以运送很多人。",
    examples: [
    { zh: "我明天坐飞机去北京。", pinyin: "Wǒ míngtiān zuò fēijī qù Běijīng.", en: "I will take a plane to Beijing tomorrow." },
    { zh: "飞机在天空中飞行。", pinyin: "Fēijī zài tiānkōng zhōng fēixíng.", en: "The airplane flies in the sky." },
    { zh: "这架飞机很大，可以坐三百个人。", pinyin: "Zhè jià fēijī hěn dà, kěyǐ zuò sānbǎi ge rén.", en: "This airplane is very large and can seat three hundred people." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "分钟": {
    explanation_zh: "分钟是时间的单位，六十秒等于一分钟。",
    examples: [
    { zh: "请等我五分钟。", pinyin: "Qǐng děng wǒ wǔ fēnzhōng.", en: "Please wait for me five minutes." },
    { zh: "这个电影有一百二十分钟。", pinyin: "Zhège diànyǐng yǒu yībǎi èrshí fēnzhōng.", en: "This movie is one hundred twenty minutes long." },
    { zh: "我每天花三十分钟做运动。", pinyin: "Wǒ měi tiān huā sānshí fēnzhōng zuò yùndòng.", en: "I spend thirty minutes exercising every day." },
    ],
    synonyms: [
    { chinese: "分", pinyin: "fēn", en: "minute" },
    ],
    antonyms: [
    ],
  },
  "高兴": {
    explanation_zh: "表示心情很好，感到快乐和满足。这是一个常用的形容词，用来描述人的情绪状态。",
    examples: [
    { zh: "我今天很高兴。", pinyin: "Wǒ jīntiān hěn gāoxìng.", en: "I am very happy today." },
    { zh: "她看到礼物时很高兴。", pinyin: "Tā kàndào lǐwù shí hěn gāoxìng.", en: "She was very happy when she saw the gift." },
    { zh: "我们一起玩，都很高兴。", pinyin: "Wǒmen yìqǐ wán, dōu hěn gāoxìng.", en: "We played together and were all very happy." },
    ],
    synonyms: [
    { chinese: "开心", pinyin: "kāixīn", en: "happy; joyful" },
    { chinese: "快乐", pinyin: "kuàilè", en: "happy; joyful" },
    { chinese: "愉快", pinyin: "yúkuài", en: "pleasant; delightful" },
    ],
    antonyms: [
    { chinese: "难过", pinyin: "nánguò", en: "sad; unhappy" },
    { chinese: "伤心", pinyin: "shāngxīn", en: "sad; heartbroken" },
    ],
  },
  "个": {
    explanation_zh: "一个量词，用来计算可数的人或物。它是最常用的量词，可以用在很多名词前面。",
    examples: [
    { zh: "我有一个苹果。", pinyin: "Wǒ yǒu yī ge píngguǒ.", en: "I have one apple." },
    { zh: "他有三个朋友。", pinyin: "Tā yǒu sān ge péngyou.", en: "He has three friends." },
    { zh: "这是一个很好的主意。", pinyin: "Zhè shì yī ge hěn hǎo de zhǔyì.", en: "This is a very good idea." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "工作": {
    explanation_zh: "指人每天做的事情，特别是为了赚钱而做的职业或任务。这是一个很重要的日常用语。",
    examples: [
    { zh: "我的工作很忙。", pinyin: "Wǒ de gōngzuò hěn máng.", en: "My work is very busy." },
    { zh: "她在公司工作。", pinyin: "Tā zài gōngsī gōngzuò.", en: "She works at a company." },
    { zh: "他找到了一个新的工作。", pinyin: "Tā zhǎodàole yī ge xīn de gōngzuò.", en: "He found a new job." },
    ],
    synonyms: [
    { chinese: "工作", pinyin: "gōngzuò", en: "job; work" },
    { chinese: "职业", pinyin: "zhíyè", en: "profession; occupation" },
    ],
    antonyms: [
    ],
  },
  "狗": {
    explanation_zh: "一种常见的动物，是人类的宠物。狗很聪明，对主人很忠诚。",
    examples: [
    { zh: "我有一只狗。", pinyin: "Wǒ yǒu yī zhī gǒu.", en: "I have a dog." },
    { zh: "这只狗很可爱。", pinyin: "Zhè zhī gǒu hěn kě'ài.", en: "This dog is very cute." },
    { zh: "狗是人类最好的朋友。", pinyin: "Gǒu shì rénlèi zuì hǎo de péngyou.", en: "Dogs are man's best friend." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "汉语": {
    explanation_zh: "中国的语言，也叫中文。学习汉语可以了解中国的文化和历史。",
    examples: [
    { zh: "我在学习汉语。", pinyin: "Wǒ zài xuéxí Hànyǔ.", en: "I am studying Chinese language." },
    { zh: "汉语很有意思。", pinyin: "Hànyǔ hěn yǒu yìsi.", en: "Chinese language is very interesting." },
    { zh: "你会说汉语吗？", pinyin: "Nǐ huì shuōhuà Hànyǔ ma?", en: "Can you speak Chinese?" },
    ],
    synonyms: [
    { chinese: "中文", pinyin: "Zhōngwén", en: "Chinese language" },
    ],
    antonyms: [
    ],
  },
  "好": {
    explanation_zh: "表示事物令人满意、符合要求或具有正面品质。这是一个常用的形容词，可以用来描述人、事物或情况。",
    examples: [
    { zh: "这个苹果很好吃。", pinyin: "Zhège píngguǒ hěn hǎochī.", en: "This apple tastes very good." },
    { zh: "她是一个好学生。", pinyin: "Tā shì yīgè hǎo xuésheng.", en: "She is a good student." },
    { zh: "今天天气很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", en: "The weather is very nice today." },
    ],
    synonyms: [
    { chinese: "优秀", pinyin: "yōuxiù", en: "excellent" },
    { chinese: "棒", pinyin: "bàng", en: "great" },
    ],
    antonyms: [
    { chinese: "坏", pinyin: "huài", en: "bad" },
    { chinese: "差", pinyin: "chà", en: "poor" },
    ],
  },
  "号": {
    explanation_zh: "用来表示序列中的位置或月份中的日期。也可以表示电话号码、房间号等各种编号。",
    examples: [
    { zh: "今天是十月五号。", pinyin: "Jīntiān shì shíyuè wǔ hào.", en: "Today is October 5th." },
    { zh: "我的电话号码是多少？", pinyin: "Wǒ de diànhuà hàomǎ shì duōshao?", en: "What is my phone number?" },
    { zh: "他住在三号房间。", pinyin: "Tā zhù zài sān hào fángjiān.", en: "He lives in room number 3." },
    ],
    synonyms: [
    { chinese: "数字", pinyin: "shùzì", en: "number" },
    ],
    antonyms: [
    ],
  },
  "喝": {
    explanation_zh: "表示用嘴把液体或饮料送入体内的动作。这是一个常见的日常动词。",
    examples: [
    { zh: "我每天喝水。", pinyin: "Wǒ měitiān hē shuǐ.", en: "I drink water every day." },
    { zh: "你想喝茶吗？", pinyin: "Nǐ xiǎng hē chá ma?", en: "Would you like to drink tea?" },
    { zh: "他喝了一杯咖啡。", pinyin: "Tā hēle yībēi kāfēi.", en: "He drank a cup of coffee." },
    ],
    synonyms: [
    ],
    antonyms: [
    ],
  },
  "和": {
    explanation_zh: "用来连接两个词或短语，表示并列关系。也可以表示伴随或陪同的意思。",
    examples: [
    { zh: "我喜欢苹果和橙子。", pinyin: "Wǒ xǐhuān píngguǒ hé chéngzi.", en: "I like apples and oranges." },
    { zh: "他和我一起去公园。", pinyin: "Tā hé wǒ yīqǐ qù gōngyuán.", en: "He went to the park with me." },
    { zh: "妈妈和爸爸在家。", pinyin: "Māma hé bàba zài jiā.", en: "Mom and Dad are at home." },
    ],
    synonyms: [
    { chinese: "与", pinyin: "yǔ", en: "and; with" },
    ],
    antonyms: [
    ],
  },
  "很": {
    explanation_zh: "用来加强形容词或副词的程度，表示某种性质或状态达到相当的程度。",
    examples: [
    { zh: "这个电影很有趣。", pinyin: "Zhège diànyǐng hěn yǒuqù.", en: "This movie is very interesting." },
    { zh: "她很聪明。", pinyin: "Tā hěn cōngming.", en: "She is very smart." },
    { zh: "今天很冷。", pinyin: "Jīntiān hěn lěng.", en: "It is very cold today." },
    ],
    synonyms: [
    { chinese: "非常", pinyin: "fēicháng", en: "very" },
    { chinese: "特别", pinyin: "tèbié", en: "especially" },
    ],
    antonyms: [
    ],
  },
};
